<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/07 18:10:42

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=ofertix',
  'username' => 'ofertix',
  'password' => 'ofertix',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
