<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/10/07 18:33:04
sfConfig::add(array(
  'app_menus_frontend_menu' => array (
  'name' => 'Admin menu',
  'children' => 
  array (
    'home' => 
    array (
      'label' => 'Home',
      'route' => '@homepage',
    ),
    'signin' => 
    array (
      'label' => 'Sign in',
      'route' => '@sf_guard_signin',
      'requires_no_auth' => true,
    ),
    'signout' => 
    array (
      'label' => 'Sign out',
      'route' => '@sf_guard_signout',
      'requires_auth' => true,
    ),
    'contabilidad' => 
    array (
      'label' => 'Contabilidad',
      'route' => '@contabilidad',
      'credentials' => 
      array (
        0 => 'contabilidad',
      ),
      'children' => 
      array (
        'contabilidad_opcion1' => 
        array (
          'label' => 'Opcion 1',
          'route' => '@contabilidad_opcion1',
          'credentials' => 
          array (
            0 => 'contabilidad',
            1 => 'impares',
          ),
        ),
        'contabilidad_opcion2' => 
        array (
          'label' => 'Opcion 2',
          'route' => '@contabilidad_opcion2',
          'credentials' => 
          array (
            0 => 'contabilidad',
            1 => 'pares',
          ),
        ),
        'contabilidad_opcion3' => 
        array (
          'label' => 'Opcion 3',
          'route' => '@contabilidad_opcion3',
          'credentials' => 
          array (
            0 => 'contabilidad',
            1 => 'impares',
          ),
        ),
        'contabilidad_opcion4' => 
        array (
          'label' => 'Opcion 4',
          'route' => '@contabilidad_opcion4',
          'credentials' => 
          array (
            0 => 'contabilidad',
            1 => 'pares',
          ),
        ),
      ),
    ),
    'produccion' => 
    array (
      'label' => 'Produccion',
      'route' => '@produccion',
      'credentials' => 
      array (
        0 => 'produccion',
      ),
      'children' => 
      array (
        'produccion_opcion1' => 
        array (
          'label' => 'Opcion 1',
          'route' => '@produccion_opcion1',
          'credentials' => 
          array (
            0 => 'produccion',
            1 => 'impares',
          ),
        ),
        'produccion_opcion2' => 
        array (
          'label' => 'Opcion 2',
          'route' => '@produccion_opcion2',
          'credentials' => 
          array (
            0 => 'produccion',
            1 => 'pares',
          ),
        ),
        'produccion_opcion3' => 
        array (
          'label' => 'Opcion 3',
          'route' => '@produccion_opcion3',
          'credentials' => 
          array (
            0 => 'produccion',
            1 => 'impares',
          ),
        ),
        'produccion_opcion4' => 
        array (
          'label' => 'Opcion 4',
          'route' => '@produccion_opcion4',
          'credentials' => 
          array (
            0 => 'produccion',
            1 => 'pares',
          ),
        ),
      ),
    ),
    'comercial' => 
    array (
      'label' => 'Comercial',
      'route' => '@comercial',
      'credentials' => 
      array (
        0 => 'comercial',
      ),
      'children' => 
      array (
        'comercial_opcion1' => 
        array (
          'label' => 'Opcion 1',
          'route' => '@comercial_opcion1',
          'credentials' => 
          array (
            0 => 'comercial',
            1 => 'impares',
          ),
        ),
        'comercial_opcion2' => 
        array (
          'label' => 'Opcion 2',
          'route' => '@comercial_opcion2',
          'credentials' => 
          array (
            0 => 'comercial',
            1 => 'pares',
          ),
        ),
        'comercial_opcion3' => 
        array (
          'label' => 'Opcion 3',
          'route' => '@comercial_opcion3',
          'credentials' => 
          array (
            0 => 'comercial',
            1 => 'impares',
          ),
        ),
        'comercial_opcion4' => 
        array (
          'label' => 'Opcion 4',
          'route' => '@comercial_opcion4',
          'credentials' => 
          array (
            0 => 'comercial',
            1 => 'pares',
          ),
        ),
      ),
    ),
    'callcenter' => 
    array (
      'label' => 'Callcenter',
      'route' => '@callcenter',
      'credentials' => 
      array (
        0 => 'callcenter',
      ),
      'children' => 
      array (
        'callcenter_opcion1' => 
        array (
          'label' => 'Opcion 1',
          'route' => '@callcenter_opcion1',
          'credentials' => 
          array (
            0 => 'callcenter',
            1 => 'impares',
          ),
        ),
        'callcenter_opcion2' => 
        array (
          'label' => 'Opcion 2',
          'route' => '@callcenter_opcion2',
          'credentials' => 
          array (
            0 => 'callcenter',
            1 => 'pares',
          ),
        ),
        'callcenter_opcion3' => 
        array (
          'label' => 'Opcion 3',
          'route' => '@callcenter_opcion3',
          'credentials' => 
          array (
            0 => 'callcenter',
            1 => 'impares',
          ),
        ),
        'callcenter_opcion4' => 
        array (
          'label' => 'Opcion 4',
          'route' => '@callcenter_opcion4',
          'credentials' => 
          array (
            0 => 'callcenter',
            1 => 'pares',
          ),
        ),
      ),
    ),
    'comun' => 
    array (
      'label' => 'Comun',
      'route' => '@comun',
      'requires_auth' => true,
      'children' => 
      array (
        'comun_opcion1' => 
        array (
          'label' => 'Opcion 1',
          'route' => '@comun_opcion1',
          'credentials' => 
          array (
            0 => 'impares',
          ),
        ),
        'comun_opcion2' => 
        array (
          'label' => 'Opcion 2',
          'route' => '@comun_opcion2',
          'credentials' => 
          array (
            0 => 'pares',
          ),
        ),
        'comun_opcion3' => 
        array (
          'label' => 'Opcion 3',
          'route' => '@comun_opcion3',
          'credentials' => 
          array (
            0 => 'impares',
          ),
        ),
        'comun_opcion4' => 
        array (
          'label' => 'Opcion 4',
          'route' => '@comun_opcion4',
          'credentials' => 
          array (
            0 => 'pares',
          ),
        ),
      ),
    ),
  ),
),
));
