dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=ofertix'
      username: ofertix
      password: ofertix
      encoding: utf8
      persistent: true
      pooling: true
