opcion1:
    is_secure:   on        # Only for authenticated users
    credentials: [ impares, comercial ]     # With the admin credential

opcion2:
    is_secure:   on        # Only for authenticated users
    credentials: [ pares, comercial ]     # With the admin credential

opcion3:
    is_secure:   on        # Only for authenticated users
    credentials: [ impares, comercial ]     # With the admin credential

opcion4:
    is_secure:   on        # Only for authenticated users
    credentials: [ pares, comercial ]      # With the admin credential