opcion1:
    is_secure:   on        # Only for authenticated users
    credentials: [ impares, contabilidad ]     # With the admin credential

opcion2:
    is_secure:   on        # Only for authenticated users
    credentials: [ pares, contabilidad ]     # With the admin credential

opcion3:
    is_secure:   on        # Only for authenticated users
    credentials: [ impares, contabilidad ]     # With the admin credential

opcion4:
    is_secure:   on        # Only for authenticated users
    credentials: [ pares, contabilidad ]      # With the admin credential